create table if not exists public.solicitacoes (
  id bigint generated by default as identity primary key,
  nome_solicitante text not null,
  bairro text not null,
  tipo_servico text not null,
  descricao text not null,
  status_solicitacao text not null default 'Pendente',
  created_at timestamptz not null default now()
);

alter table public.solicitacoes enable row level security;

create policy "Permitir leitura de solicitações"
  on public.solicitacoes
  for select
  using (true);

create policy "Permitir inserção de solicitações"
  on public.solicitacoes
  for insert
  with check (true);

create policy "Permitir atualização de solicitações"
  on public.solicitacoes
  for update
  using (true)
  with check (true);
